[WIP] PermissionRequestImpl was deleted. II
Fixes error for Android:
error: enumeration values 'kWidevine' and 'kBraveEthereum' not handled in switch [-Werror,-Wswitch]

WIP: Do we still need SupportsLifetime method?

Chromium change:

https://source.chromium.org/chromium/chromium/src/+/5327d8b59d2550161c49f7180cb05b1afbbea609

commit 5327d8b59d2550161c49f7180cb05b1afbbea609
Author: Bret Sepulveda <bsep@chromium.org>
Date:   Wed Jul 21 17:44:23 2021 +0000

    Delete PermissionRequestImpl.

    This patch deletes PermissionRequestImpl, making PermissionRequest a
    concrete class with all of its functionality. PermissionRequest also now
    takes a RequestType rather than a ContentSettingsType, which allows it
    to support request types that don't have an associated
    ContentSettingsType (e.g. multiple downloads). Common functionality
    among the children of PermissionRequest is moved to the parent class.

    Bug: 1110905